/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Proposal = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'votesYes' : IDL.Nat,
  'recipient' : IDL.Principal,
  'description' : IDL.Text,
  'deadline' : Time,
  'votesAbstain' : IDL.Nat,
  'votesNo' : IDL.Nat,
  'executed' : IDL.Bool,
  'amount' : IDL.Nat,
});
export const Token = IDL.Record({
  'decimals' : IDL.Nat,
  'name' : IDL.Text,
  'totalSupply' : IDL.Nat,
  'symbol' : IDL.Text,
});

export const idlService = IDL.Service({
  'createProposal' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Principal, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'finalizeProposal' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllProposals' : IDL.Func([], [IDL.Vec(Proposal)], ['query']),
  'getBalance' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getProposal' : IDL.Func([IDL.Nat], [Proposal], ['query']),
  'getTokenInfo' : IDL.Func([], [Token], ['query']),
  'getTreasuryBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'transfer' : IDL.Func([IDL.Principal, IDL.Nat], [IDL.Bool], []),
  'voteProposal' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Proposal = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'votesYes' : IDL.Nat,
    'recipient' : IDL.Principal,
    'description' : IDL.Text,
    'deadline' : Time,
    'votesAbstain' : IDL.Nat,
    'votesNo' : IDL.Nat,
    'executed' : IDL.Bool,
    'amount' : IDL.Nat,
  });
  const Token = IDL.Record({
    'decimals' : IDL.Nat,
    'name' : IDL.Text,
    'totalSupply' : IDL.Nat,
    'symbol' : IDL.Text,
  });
  
  return IDL.Service({
    'createProposal' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Principal, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'finalizeProposal' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllProposals' : IDL.Func([], [IDL.Vec(Proposal)], ['query']),
    'getBalance' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getProposal' : IDL.Func([IDL.Nat], [Proposal], ['query']),
    'getTokenInfo' : IDL.Func([], [Token], ['query']),
    'getTreasuryBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'transfer' : IDL.Func([IDL.Principal, IDL.Nat], [IDL.Bool], []),
    'voteProposal' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };