/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Proposal {
  'id' : bigint,
  'title' : string,
  'creator' : Principal,
  'votesYes' : bigint,
  'recipient' : Principal,
  'description' : string,
  'deadline' : Time,
  'votesAbstain' : bigint,
  'votesNo' : bigint,
  'executed' : boolean,
  'amount' : bigint,
}
export type Time = bigint;
export interface Token {
  'decimals' : bigint,
  'name' : string,
  'totalSupply' : bigint,
  'symbol' : string,
}
export interface _SERVICE {
  'createProposal' : ActorMethod<
    [string, string, bigint, Principal, bigint],
    bigint
  >,
  'finalizeProposal' : ActorMethod<[bigint], boolean>,
  'getAllProposals' : ActorMethod<[], Array<Proposal>>,
  'getBalance' : ActorMethod<[Principal], bigint>,
  'getProposal' : ActorMethod<[bigint], Proposal>,
  'getTokenInfo' : ActorMethod<[], Token>,
  'getTreasuryBalance' : ActorMethod<[], bigint>,
  'transfer' : ActorMethod<[Principal, bigint], boolean>,
  'voteProposal' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];